### ISSUE TITLE
不知道怎么回事，启动不了

### ISSUE THREAD

**Issue by xiwuou** [FarseaSH/hugo-theme-moments#5]
→ hugo server -D
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x48 pc=0x103e49b0c]

goroutine 1 [running]:
github.com/gohugoio/hugo/hugolib.newHugoSites({{0x104e8d250, 0x1400011f470}, 0x1400052d1c0, 0x0, {0x0, 0x0}, {0x104e891d0, 0x140005311d0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/gohugoio/hugo/hugolib/hugo_sites.go:390 +0x82c
github.com/gohugoio/hugo/hugolib.NewHugoSites({{0x104e8d250, 0x1400011f470}, 0x1400052d1c0, 0x0, {0x0, 0x0}, {0x104e891d0, 0x140005311d0}, {0x0, 0x0, ...}, ...})
        github.com/gohugoio/hugo/hugolib/hugo_sites.go:519 +0x12c
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig.func3()
        github.com/gohugoio/hugo/commands/commandeer.go:417 +0x4e8
sync.(*Once).doSlow(0x14000691b40, 0x1400081f950)
        sync/once.go:68 +0x10c
sync.(*Once).Do(...)
        sync/once.go:59
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig(0x14000015420)
        github.com/gohugoio/hugo/commands/commandeer.go:375 +0x83c
github.com/gohugoio/hugo/commands.newCommandeer(0x1, 0x1, 0x1, 0x14000015180, {0x104e404a0, 0x14000053e00}, 0x14000279b60, {0x0, 0x0, 0x0})
        github.com/gohugoio/hugo/commands/commandeer.go:193 +0x2c4
github.com/gohugoio/hugo/commands.initializeConfig(0x1, 0x1, 0x1, 0x14000015180, {0x104e404a0, 0x14000053e00}, 0x14000279b60)
        github.com/gohugoio/hugo/commands/hugo.go:125 +0x60
github.com/gohugoio/hugo/commands.(*serverCmd).server(0x14000053e00, 0x140001e2f00, {0x140002c3d70, 0x0, 0x1})
        github.com/gohugoio/hugo/commands/server.go:242 +0x1b8
github.com/spf13/cobra.(*Command).execute(0x140001e2f00, {0x140002c3d60, 0x1, 0x1})
        github.com/spf13/cobra@v1.2.1/command.go:856 +0x668
github.com/spf13/cobra.(*Command).ExecuteC(0x14000850f00)
        github.com/spf13/cobra@v1.2.1/command.go:974 +0x410
github.com/gohugoio/hugo/commands.Execute({0x1400011e0a0, 0x2, 0x2})
        github.com/gohugoio/hugo/commands/hugo.go:92 +0xa4
main.main()
        github.com/gohugoio/hugo/main.go:23 +0x60

**Comment by xiwuou** [comment]
我在m1上使用，启动不了，报错。

**Comment by xiwuou** [comment]
对不起，那是我的错。
我在 baseURL 中写了 127.0.0.1:1313

我是傻逼
